// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYhT3Xf3dTfjnv7ZKGFJKxeSHkpJJ4raU',
    appId: '1:165315212535:web:7e3136743685ecc7ad4ff2',
    messagingSenderId: '165315212535',
    projectId: 'el-massa-consult',
    authDomain: 'el-massa-consult.firebaseapp.com',
    storageBucket: 'el-massa-consult.firebasestorage.app',
    measurementId: 'G-95P70SG3BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-W3esuAe7NPBJpIfctAd-fbYTw_5CQbc',
    appId: '1:165315212535:android:612a01df1bbb9015ad4ff2',
    messagingSenderId: '165315212535',
    projectId: 'el-massa-consult',
    storageBucket: 'el-massa-consult.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9cnUAAx7kBpi1RzhEAcMe0G9ECRumF0',
    appId: '1:165315212535:ios:36046f22df1050b6ad4ff2',
    messagingSenderId: '165315212535',
    projectId: 'el-massa-consult',
    storageBucket: 'el-massa-consult.firebasestorage.app',
    androidClientId: '165315212535-26s6eqjlsnjtufqmvr0ncsmskbuhoro6.apps.googleusercontent.com',
    iosClientId: '165315212535-32vfqdf2k5k3vn3ukkautb5avevn5cad.apps.googleusercontent.com',
    iosBundleId: 'com.example.ElMassaConsult',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC9cnUAAx7kBpi1RzhEAcMe0G9ECRumF0',
    appId: '1:165315212535:ios:36046f22df1050b6ad4ff2',
    messagingSenderId: '165315212535',
    projectId: 'el-massa-consult',
    storageBucket: 'el-massa-consult.firebasestorage.app',
    androidClientId: '165315212535-26s6eqjlsnjtufqmvr0ncsmskbuhoro6.apps.googleusercontent.com',
    iosClientId: '165315212535-32vfqdf2k5k3vn3ukkautb5avevn5cad.apps.googleusercontent.com',
    iosBundleId: 'com.example.ElMassaConsult',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYhT3Xf3dTfjnv7ZKGFJKxeSHkpJJ4raU',
    appId: '1:165315212535:web:5ecb9d5756b278ccad4ff2',
    messagingSenderId: '165315212535',
    projectId: 'el-massa-consult',
    authDomain: 'el-massa-consult.firebaseapp.com',
    storageBucket: 'el-massa-consult.firebasestorage.app',
    measurementId: 'G-40WQ3JP4QS',
  );

}